environment:
  matrix:
    - CHANNEL: stable
      TARGET: x86_64-pc-windows-msvc
    - CHANNEL: stable
      TARGET: x86_64-pc-windows-gnu
    - CHANNEL: beta
      TARGET: x86_64-pc-windows-msvc
    - CHANNEL: nightly
      TARGET: x86_64-pc-windows-msvc

matrix:
  allow_failures:
    - channel: nightly

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %CHANNEL% --default-host %TARGET%
  - set PATH = %PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo test --verbose